name: "cqs_mvp"
profile: "cqs_mvp"


# Configure paths 
model-paths: [".dbt/models"]
test-paths: [".dbt/tests"]
# analysis-paths: [".dbt/analyses"]
# seed-paths: [".dbt/seeds"]
# macro-paths: [".dbt/macros"]
# snapshot-paths: [".dbt/snapshots"]

target-path: ".dbt/target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"